# Generated by Django 4.1.3 on 2023-01-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bodt',
            new_name='body',
        ),
    ]
